export const LMS_PALETTE = {
  primary: 'oklch(var(--primary))',
  primaryActive: 'oklch(var(--primary))',
  canvas: 'oklch(var(--background))',
  surfaceSoft: 'oklch(var(--secondary))',
  surfaceCard: 'oklch(var(--card))',
  surfaceCreamStrong: 'oklch(var(--muted))',
  border: 'oklch(var(--border))',
  ink: 'oklch(var(--foreground))',
  body: 'oklch(var(--foreground))',
  muted: 'oklch(var(--muted-foreground))',
  mutedSoft: 'oklch(var(--muted-foreground))',
  dark: 'oklch(var(--card))',
  onDark: 'oklch(var(--card-foreground))',
  onDarkSoft: 'oklch(var(--muted-foreground))',
  teal: '#5db8a6',
  amber: '#e8a55a',
  success: '#5db872',
  warning: '#d4a017',
  error: '#c64545',
} as const
