import type { DeptConfig, OrgPerson } from './orgchart.types'

export const DEPT_CONFIG: Record<string, DeptConfig> = {
  Executive:   { dot: '#cc785c', avatarBg: '#fdf1eb', avatarText: '#cc785c', badgeBg: '#fdf1eb', badgeText: '#a9583e' },
  Engineering: { dot: '#cc785c', avatarBg: '#fdf1eb', avatarText: '#cc785c', badgeBg: '#fdf1eb', badgeText: '#a9583e' },
  Sales:       { dot: '#5db872', avatarBg: '#edfbf1', avatarText: '#2d7a40', badgeBg: '#edfbf1', badgeText: '#2d7a40' },
  Marketing:   { dot: '#8b5cf6', avatarBg: '#f5f3ff', avatarText: '#6d28d9', badgeBg: '#f5f3ff', badgeText: '#6d28d9' },
  HR:          { dot: '#5db8a6', avatarBg: '#e0f5f2', avatarText: '#357a70', badgeBg: '#e0f5f2', badgeText: '#357a70' },
  Finance:     { dot: '#64748b', avatarBg: '#f1f5f9', avatarText: '#475569', badgeBg: '#f1f5f9', badgeText: '#475569' },
  Product:     { dot: '#e8a55a', avatarBg: '#fdf0e0', avatarText: '#9a6b2a', badgeBg: '#fdf0e0', badgeText: '#9a6b2a' },
}

export const DEPT_NAMES = ['All Departments', ...Object.keys(DEPT_CONFIG).filter(d => d !== 'Executive')]

export const ORG_TREE: OrgPerson = {
  id: 'ceo',
  name: 'Nguyễn Văn Hùng',
  initials: 'HN',
  title: 'Chief Executive Officer',
  department: 'Executive',
  email: 'hung.nguyen@digifnb.vn',
  phone: '+84 90 123 4567',
  location: 'Ho Chi Minh City',
  joinDate: 'Jan 2018',
  children: [
    {
      id: 'vp-eng',
      name: 'Trần Minh Khoa',
      initials: 'KT',
      title: 'VP of Engineering',
      department: 'Engineering',
      email: 'khoa.tran@digifnb.vn',
      phone: '+84 91 234 5678',
      location: 'Ho Chi Minh City',
      joinDate: 'Mar 2019',
      reportsToId: 'ceo',
      children: [
        {
          id: 'head-backend',
          name: 'Lê Thị Hoa',
          initials: 'HL',
          title: 'Head of Backend',
          department: 'Engineering',
          email: 'hoa.le@digifnb.vn',
          phone: '+84 92 345 6789',
          location: 'Ho Chi Minh City',
          joinDate: 'Jun 2020',
          reportsToId: 'vp-eng',
          children: [
            {
              id: 'senior-dev-1',
              name: 'Phạm Văn Đức',
              initials: 'DP',
              title: 'Senior Backend Developer',
              department: 'Engineering',
              email: 'duc.pham@digifnb.vn',
              phone: '+84 93 456 7890',
              location: 'Ho Chi Minh City',
              joinDate: 'Sep 2021',
              reportsToId: 'head-backend',
              children: [],
            },
            {
              id: 'senior-dev-2',
              name: 'Vũ Thị Lan',
              initials: 'LV',
              title: 'Backend Developer',
              department: 'Engineering',
              email: 'lan.vu@digifnb.vn',
              phone: '+84 94 567 8901',
              location: 'Hanoi',
              joinDate: 'Jan 2022',
              reportsToId: 'head-backend',
              children: [],
            },
          ],
        },
        {
          id: 'head-frontend',
          name: 'Hoàng Minh Tú',
          initials: 'TH',
          title: 'Head of Frontend',
          department: 'Engineering',
          email: 'tu.hoang@digifnb.vn',
          phone: '+84 95 678 9012',
          location: 'Ho Chi Minh City',
          joinDate: 'Aug 2020',
          reportsToId: 'vp-eng',
          children: [
            {
              id: 'frontend-dev-1',
              name: 'Bùi Thị Mai',
              initials: 'MB',
              title: 'Frontend Developer',
              department: 'Engineering',
              email: 'mai.bui@digifnb.vn',
              phone: '+84 96 789 0123',
              location: 'Ho Chi Minh City',
              joinDate: 'Mar 2022',
              reportsToId: 'head-frontend',
              children: [],
            },
            {
              id: 'frontend-dev-2',
              name: 'Đặng Văn Nam',
              initials: 'ND',
              title: 'UI/UX Designer',
              department: 'Engineering',
              email: 'nam.dang@digifnb.vn',
              phone: '+84 97 890 1234',
              location: 'Da Nang',
              joinDate: 'Jun 2022',
              reportsToId: 'head-frontend',
              children: [],
            },
          ],
        },
      ],
    },
    {
      id: 'vp-sales',
      name: 'Phan Thị Linh',
      initials: 'LP',
      title: 'VP of Sales & Marketing',
      department: 'Sales',
      email: 'linh.phan@digifnb.vn',
      phone: '+84 98 901 2345',
      location: 'Ho Chi Minh City',
      joinDate: 'Jul 2019',
      reportsToId: 'ceo',
      children: [
        {
          id: 'sales-mgr',
          name: 'Ngô Văn Hải',
          initials: 'HN',
          title: 'Sales Manager',
          department: 'Sales',
          email: 'hai.ngo@digifnb.vn',
          phone: '+84 99 012 3456',
          location: 'Ho Chi Minh City',
          joinDate: 'Nov 2020',
          reportsToId: 'vp-sales',
          children: [
            {
              id: 'sales-rep-1',
              name: 'Trịnh Thị Xuân',
              initials: 'XT',
              title: 'Senior Sales Executive',
              department: 'Sales',
              email: 'xuan.trinh@digifnb.vn',
              phone: '+84 90 123 4568',
              location: 'Ho Chi Minh City',
              joinDate: 'Feb 2022',
              reportsToId: 'sales-mgr',
              children: [],
            },
          ],
        },
        {
          id: 'mktg-mgr',
          name: 'Cao Minh Đức',
          initials: 'DC',
          title: 'Marketing Manager',
          department: 'Marketing',
          email: 'duc.cao@digifnb.vn',
          phone: '+84 91 234 5679',
          location: 'Ho Chi Minh City',
          joinDate: 'Apr 2021',
          reportsToId: 'vp-sales',
          children: [
            {
              id: 'designer-1',
              name: 'Lưu Thị Hương',
              initials: 'HL',
              title: 'Creative Designer',
              department: 'Marketing',
              email: 'huong.luu@digifnb.vn',
              phone: '+84 92 345 6780',
              location: 'Ho Chi Minh City',
              joinDate: 'Aug 2022',
              reportsToId: 'mktg-mgr',
              children: [],
            },
          ],
        },
      ],
    },
    {
      id: 'vp-people',
      name: 'Đinh Thị Nga',
      initials: 'ND',
      title: 'VP of People & Operations',
      department: 'HR',
      email: 'nga.dinh@digifnb.vn',
      phone: '+84 93 456 7891',
      location: 'Ho Chi Minh City',
      joinDate: 'Feb 2019',
      reportsToId: 'ceo',
      children: [
        {
          id: 'hr-mgr',
          name: 'Mai Văn Sơn',
          initials: 'SM',
          title: 'HR Manager',
          department: 'HR',
          email: 'son.mai@digifnb.vn',
          phone: '+84 94 567 8902',
          location: 'Ho Chi Minh City',
          joinDate: 'May 2021',
          reportsToId: 'vp-people',
          children: [
            {
              id: 'hr-specialist',
              name: 'Tô Thị Bích',
              initials: 'BT',
              title: 'HR Specialist',
              department: 'HR',
              email: 'bich.to@digifnb.vn',
              phone: '+84 95 678 9013',
              location: 'Ho Chi Minh City',
              joinDate: 'Sep 2022',
              reportsToId: 'hr-mgr',
              children: [],
            },
          ],
        },
        {
          id: 'finance-mgr',
          name: 'Hồ Văn Long',
          initials: 'LH',
          title: 'Finance Manager',
          department: 'Finance',
          email: 'long.ho@digifnb.vn',
          phone: '+84 96 789 0124',
          location: 'Ho Chi Minh City',
          joinDate: 'Jul 2020',
          reportsToId: 'vp-people',
          children: [
            {
              id: 'accountant-1',
              name: 'Kiều Thị Thu',
              initials: 'TK',
              title: 'Senior Accountant',
              department: 'Finance',
              email: 'thu.kieu@digifnb.vn',
              phone: '+84 97 890 1235',
              location: 'Ho Chi Minh City',
              joinDate: 'Dec 2021',
              reportsToId: 'finance-mgr',
              children: [],
            },
          ],
        },
      ],
    },
  ],
}

export function findPersonById(tree: OrgPerson, id: string): OrgPerson | null {
  if (tree.id === id) return tree
  for (const child of tree.children) {
    const found = findPersonById(child, id)
    if (found) return found
  }
  return null
}

export function countDirectReports(person: OrgPerson): number {
  return person.children.length
}
